# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        MainWindow.setMinimumSize(QtCore.QSize(600, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/infrastructure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color:  rgb(255, 228, 228)rgb(237, 237, 237);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.iconLabel = QtWidgets.QLabel(self.centralwidget)
        self.iconLabel.setMinimumSize(QtCore.QSize(42, 42))
        self.iconLabel.setMaximumSize(QtCore.QSize(42, 42))
        self.iconLabel.setStyleSheet("border-image: url(:/images/infrastructure.png);")
        self.iconLabel.setText("")
        self.iconLabel.setObjectName("iconLabel")
        self.horizontalLayout.addWidget(self.iconLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout.addWidget(self.titleLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.formWidget = QtWidgets.QWidget(self.centralwidget)
        self.formWidget.setMinimumSize(QtCore.QSize(20, 20))
        self.formWidget.setObjectName("formWidget")
        self.verticalLayout_2.addWidget(self.formWidget)
        self.firstLine = QtWidgets.QFrame(self.centralwidget)
        self.firstLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.firstLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.firstLine.setObjectName("firstLine")
        self.verticalLayout_2.addWidget(self.firstLine)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.frameForm = QtWidgets.QFrame(self.centralwidget)
        self.frameForm.setMinimumSize(QtCore.QSize(559, 150))
        self.frameForm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameForm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameForm.setObjectName("frameForm")
        self.formGroupBox = QtWidgets.QGroupBox(self.frameForm)
        self.formGroupBox.setGeometry(QtCore.QRect(20, 10, 281, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(False)
        self.formGroupBox.setFont(font)
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setObjectName("formLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.usernameLabel = QtWidgets.QLabel(self.formGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setObjectName("usernameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.usernameLabel)
        self.usernameEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.usernameEdit.setObjectName("usernameEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.usernameEdit)
        self.passwordLabel = QtWidgets.QLabel(self.formGroupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.passwordEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.passwordEdit.setObjectName("passwordEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.passwordEdit)
        self.verticalLayout.addWidget(self.frameForm)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.processLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.processLabel.setFont(font)
        self.processLabel.setObjectName("processLabel")
        self.verticalLayout_3.addWidget(self.processLabel)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.reportLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.reportLabel.setFont(font)
        self.reportLabel.setObjectName("reportLabel")
        self.verticalLayout_3.addWidget(self.reportLabel)
        self.reportEdit = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reportEdit.sizePolicy().hasHeightForWidth())
        self.reportEdit.setSizePolicy(sizePolicy)
        self.reportEdit.setObjectName("reportEdit")
        self.verticalLayout_3.addWidget(self.reportEdit)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget_9 = QtWidgets.QWidget(self.centralwidget)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_8.addWidget(self.widget_9)
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout_8.addWidget(self.loginButton)
        self.widget_7 = QtWidgets.QWidget(self.centralwidget)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_8.addWidget(self.widget_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.developedbyLabel = QtWidgets.QLabel(self.centralwidget)
        self.developedbyLabel.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(8)
        self.developedbyLabel.setFont(font)
        self.developedbyLabel.setObjectName("developedbyLabel")
        self.verticalLayout_3.addWidget(self.developedbyLabel)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SITU"))
        self.titleLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#4597f7;\">SITU</span></p></body></html>"))
        self.formGroupBox.setTitle(_translate("MainWindow", "Login"))
        self.usernameLabel.setText(_translate("MainWindow", "Username"))
        self.passwordLabel.setText(_translate("MainWindow", "Password"))
        self.processLabel.setText(_translate("MainWindow", "Process"))
        self.reportLabel.setText(_translate("MainWindow", "Report"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.developedbyLabel.setText(_translate("MainWindow", "Developed by: DIEGO LÓPEZ"))
import gui.Images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
